In [1]:
from get_data import data_prep

In [2]:
data_prep.download_data(["069500.KS", "229200.KS",
             "133690.KS", "143850.KS",
             "114260.KS", "153130.KS",
             "157450.KS"
             ]
,'2000-01-01', '2022-12-31','1d')

[*********************100%%**********************]  7 of 7 completed

Price          Adj Close                                              \
Ticker         069500.KS 114260.KS     133690.KS 143850.KS 153130.KS
Date
2007-01-29  13827.810547       NaN           NaN       NaN       NaN
2007-01-30  13881.470703       NaN           NaN       NaN       NaN
2007-01-31  13808.642578       NaN           NaN       NaN       NaN
2007-02-01  14007.931641       NaN           NaN       NaN       NaN
2007-02-02  14306.875000       NaN           NaN       NaN       NaN
...                  ...       ...           ...       ...       ...
2022-12-23  29224.820312   56600.0  62387.347656   44400.0  104420.0
2022-12-26  29268.318359   56570.0  62288.078125   44680.0  104420.0
2022-12-27  29476.136719   56490.0  62466.765625   44915.0  104420.0
2022-12-28  29128.162109   56425.0  61052.144531   44500.0  104475.0
2022-12-29  28606.203125   56390.0  60357.238281   43935.0  104485.0

Price                                  Close                      ...  \
Ticker     157450.KS     229200.KS 069500.KS 114260.KS 133690.KS  ...
Date                                                              ...
2007-01-29       NaN           NaN   18040.0       NaN       NaN  ...
2007-01-30       NaN           NaN   18110.0       NaN       NaN  ...
2007-01-31       NaN           NaN   18015.0       NaN       NaN  ...
2007-02-01       NaN           NaN   18275.0       NaN       NaN  ...
2007-02-02       NaN           NaN   18665.0       NaN       NaN  ...
...              ...           ...       ...       ...       ...  ...
2022-12-23  101995.0   9727.398438   30235.0   56600.0   62845.0  ...
2022-12-26  101995.0   9911.403320   30280.0   56570.0   62745.0  ...
2022-12-27  102005.0  10055.623047   30495.0   56490.0   62925.0  ...
2022-12-28  102040.0   9767.182617   30135.0   56425.0   61500.0  ...
2022-12-29  102045.0   9588.151367   29595.0   56390.0   60800.0  ...

Price           Open                         Volume                      \
Ticker     153130.KS 157450.KS 229200.KS  069500.KS 114260.KS 133690.KS
Date
2007-01-29       NaN       NaN       NaN   433267.0       NaN       NaN
2007-01-30       NaN       NaN       NaN   205208.0       NaN       NaN
2007-01-31       NaN       NaN       NaN   553305.0       NaN       NaN
2007-02-01       NaN       NaN       NaN   515988.0       NaN       NaN
2007-02-02       NaN       NaN       NaN  1031912.0       NaN       NaN
...              ...       ...       ...        ...       ...       ...
2022-12-23  104375.0  101995.0   10025.0  7174835.0    2247.0  139946.0
2022-12-26  104425.0  101995.0    9790.0  5992640.0    1055.0   85418.0
2022-12-27  104400.0  102000.0   10010.0  2912644.0    5478.0   68616.0
2022-12-28  104460.0  102005.0   10025.0  7272311.0    3156.0  119443.0
2022-12-29  104485.0  105995.0    9775.0  5512087.0     876.0   91674.0

Price
Ticker     143850.KS  153130.KS 157450.KS   229200.KS
Date
2007-01-29       NaN        NaN       NaN         NaN
2007-01-30       NaN        NaN       NaN         NaN
2007-01-31       NaN        NaN       NaN         NaN
2007-02-01       NaN        NaN       NaN         NaN
2007-02-02       NaN        NaN       NaN         NaN
...              ...        ...       ...         ...
2022-12-23  189735.0   712813.0    6850.0   9985762.0
2022-12-26   16694.0   472548.0   95575.0  13077980.0
2022-12-27  629829.0   749717.0  874098.0  10295220.0
2022-12-28   11531.0   926705.0   62584.0   8202033.0
2022-12-29   37132.0  1271471.0    3557.0   9128235.0

[3386 rows x 42 columns]