In [1]:
import numpy as np
import pandas as pd
from dateutil.relativedelta import relativedelta
from datetime import datetime

In [2]:
from class_trial import StockData

In [3]:
# List of tickers
tic = ["069500.KS", "229200.KS",
             "133690.KS", "143850.KS",
             "114260.KS", "153130.KS",
             "157450.KS"
             ]

In [4]:
# Initializae
stock_data = StockData()

In [5]:
# Get data
data = stock_data.download_data(tic,'2000-01-01', '2022-12-31','1d')

[*********************100%%**********************]  7 of 7 completed

In [6]:
df = stock_data.get_monthly(data)

In [158]:
df

Ticker,069500.KS,114260.KS,133690.KS,143850.KS,153130.KS,157450.KS,229200.KS
Date,,,,,,,
2015-10-30,25075.0,55840.0,23860.0,24265.0,101570.0,101550.0,10645.0
2015-11-30,24490.0,55665.0,24300.0,24185.0,101625.0,101640.0,10980.0
2015-12-30,24345.0,55660.0,24695.0,24105.0,100030.0,100050.0,11015.0
2016-01-29,23525.0,55850.0,22685.0,22130.0,100160.0,100160.0,11280.0
2016-02-29,23930.0,56145.0,23395.0,22635.0,100305.0,100285.0,10440.0
...,...,...,...,...,...,...,...
2022-07-29,32385.0,56855.0,74890.0,48080.0,103505.0,101040.0,11390.0
2022-08-31,32230.0,55870.0,74495.0,46985.0,103590.0,101175.0,11395.0
2022-09-30,28275.0,55280.0,71780.0,42735.0,103735.0,101380.0,9535.0
2022-10-31,29965.0,55415.0,73240.0,45520.0,103890.0,101525.0,10035.0
2022-11-30,32075.0,56475.0,67950.0,46130.0,104180.0,101770.0,10325.0

In [7]:
df

Ticker,069500.KS,114260.KS,133690.KS,143850.KS,153130.KS,157450.KS,229200.KS
Date,,,,,,,
2015-10-30,25075.0,55840.0,23860.0,24265.0,101570.0,101550.0,10645.0
2015-11-30,24490.0,55665.0,24300.0,24185.0,101625.0,101640.0,10980.0
2015-12-30,24345.0,55660.0,24695.0,24105.0,100030.0,100050.0,11015.0
2016-01-29,23525.0,55850.0,22685.0,22130.0,100160.0,100160.0,11280.0
2016-02-29,23930.0,56145.0,23395.0,22635.0,100305.0,100285.0,10440.0
...,...,...,...,...,...,...,...
2022-07-29,32385.0,56855.0,74890.0,48080.0,103505.0,101040.0,11390.0
2022-08-31,32230.0,55870.0,74495.0,46985.0,103590.0,101175.0,11395.0
2022-09-30,28275.0,55280.0,71780.0,42735.0,103735.0,101380.0,9535.0
2022-10-31,29965.0,55415.0,73240.0,45520.0,103890.0,101525.0,10035.0
2022-11-30,32075.0,56475.0,67950.0,46130.0,104180.0,101770.0,10325.0

In [78]:
dt_ind, ret = stock_data.clean(data)

In [8]:
nasdaq = stock_data.download_data(['^IXIC'],'2000-01-01', '2022-12-31','1d')

[*********************100%%**********************]  1 of 1 completed

In [10]:
df_nasdaq = stock_data.get_monthly(nasdaq)

In [157]:
df_nasdaq

                   Close
Date
2000-01-31   3940.350098
2000-02-29   4696.689941
2000-03-31   4572.830078
2000-04-28   3860.659912
2000-05-31   3400.909912
...                  ...
2022-07-29  12390.690430
2022-08-31  11816.200195
2022-09-30  10575.620117
2022-10-31  10988.150391
2022-11-30  11468.000000

[275 rows x 1 columns]

In [12]:
from technical_indicators import technicalindicator

In [21]:
nasdaq_macd = technicalindicator.calculate_macd(df_nasdaq)[0]

In [32]:
nasdaq_5ma = technicalindicator.get_moving_average(df_nasdaq,5)
nasdaq_20ma = technicalindicator.get_moving_average(df_nasdaq,20)

In [33]:
merged_df = pd.merge(df_nasdaq, nasdaq_5ma, left_index=True, right_index=True, how='outer')
merged_df1 = pd.merge(merged_df, nasdaq_20ma, left_index=True, right_index=True, how='outer')
merged_df1 = pd.merge(merged_df1, nasdaq_macd, left_index=True, right_index=True, how='outer')

In [34]:
merged_df1.rename(columns={'Close_x': 'Close', 'Close_ma5_x': '5mo MA', 
                            'Close_ma5_y': '20mo MA', 'Close_y':'MACD'}, inplace=True)

In [38]:
nasdaq_ind = merged_df1.dropna()

In [41]:
nasdaq_ind['gc'] = nasdaq_ind['5mo MA'] > nasdaq_ind['20mo MA']

C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\510076695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasdaq_ind['gc'] = nasdaq_ind['5mo MA'] > nasdaq_ind['20mo MA']

In [71]:
nasdaq_ind['gc_ind'] = (nasdaq_ind.gc - nasdaq_ind.gc.shift(1)).replace(-1, 0)

C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\4207005477.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  nasdaq_ind['gc_ind'] = (nasdaq_ind.gc - nasdaq_ind.gc.shift(1)).replace(-1, 0)
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\4207005477.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasdaq_ind['gc_ind'] = (nasdaq_ind.gc - nasdaq_ind.gc.shift(1)).replace(-1, 0)

In [72]:
nasdaq_ind['gc_sum'] = nasdaq_ind['gc_ind'].rolling(window=6).sum()

C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\1094108485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nasdaq_ind['gc_sum'] = nasdaq_ind['gc_ind'].rolling(window=6).sum()

In [79]:
nasdaq_ind

,Close,5mo MA,20mo MA,MACD,gc,gc_ind,gc_sum
Date,,,,,,,
2001-08-31,1805.430054,2043.966016,3075.322009,-536.955161,False,NaN,NaN
2001-09-28,1498.800049,1920.478027,2953.244507,-571.761672,False,0.0,NaN
2001-10-31,1690.199951,1836.420020,2802.920007,-577.247560,False,0.0,NaN
2001-11-30,1930.579956,1790.428003,2670.807501,-555.791688,False,0.0,NaN
2001-12-31,1950.400024,1775.082007,2575.294507,-531.066635,False,0.0,NaN
...,...,...,...,...,...,...,...
2022-07-29,12390.690430,12411.195898,13786.118506,474.491977,False,0.0,0.0
2022-08-31,11816.200195,11930.332031,13732.514502,336.444240,False,0.0,0.0
2022-09-30,10575.620117,11578.528125,13607.760986,125.489406,False,0.0,0.0
2022-10-31,10988.150391,11359.880273,13497.551025,-8.310279,False,0.0,0.0
2022-11-30,11468.000000,11447.732227,13408.607520,-74.765787,False,0.0,0.0

In [90]:
ti = nasdaq_ind[(nasdaq_ind.index.month == 1) & (nasdaq_ind.index.year == 2011)]

In [103]:
(ti.Close < ti['5mo MA'])[0]

C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\1946373926.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  (ti.Close < ti['5mo MA'])[0]

False

In [145]:
odd_stock_w = 0.7
odd_bond_w = 0.3
even_stock_w = 0.5
even_bond_w = 0.5
even_passive_stock_w = 0.3
even_passive_bond_w = 0.7
odd_buy = np.array([0.2*odd_stock_w, (1/3*odd_bond_w), 0.3*odd_stock_w, 0.2*odd_stock_w, (1/3*odd_bond_w), (1/3*odd_bond_w), 0.3*odd_stock_w])          # Even 11 - Odd 4
odd_hold = np.array([0.2*odd_stock_w, (1/3*odd_bond_w), 0.3*odd_stock_w, 0.2*odd_stock_w, (1/3*odd_bond_w), (1/3*odd_bond_w), 0.0*odd_stock_w])         # Odd 5 - Odd 10
even_buy = np.array([0.2*even_stock_w, (1/3*even_bond_w), 0.4*even_stock_w, 0.4*even_stock_w, (1/3*even_bond_w), (1/3*even_bond_w), 0.0*even_stock_w])  # Odd 11 - Even 4
even_hold = np.array([0.0*even_passive_stock_w, (1/3*even_passive_bond_w), 0.5*even_passive_stock_w, 0.5*even_passive_stock_w, (1/3*even_passive_bond_w), (1/3*even_passive_bond_w), 0.0*even_passive_stock_w])  # Even 5 - Even 10
logic_sell = np.array([0.0, (1/3), 0.0, 0.0, (1/3), (1/3), 0.0])

In [177]:
def algo2(test1,ret,nasdaq_ind):
    #########################################################################
    # Halloween Adjusted + Logic: 
        # Sell signal: (Sell all stocks, go all bonds)
            # monthly closing price closes below 5 month moving average 
            # (Exception 1):
                # When 5-month MA > 20-month MA within the past 6 months 
            # (Exception 2):
                # If odd year
        # Re-entry: 
            # monthly closing price closes above 5 month moving average 
    #########################################################################

    port_list = [10000000000]  # Seed money 
    port = port_list[0]

    mkt_val = []
    cash_rem = []
    strat = []

    # Indicator for whether we have entered the market or not
    invested = False
    #logic_sell_ind = False 

    # Start Backtest! 
    for i in range(len(test1)):

        if invested == False: 
            # We are not yet invested in any assets. All Cash 
            pass
        else: 
            # Now, we assume that we have # of shares, mkt value of each asset (i.e. we are invested)
            #print("Print daily return", test1['Date'][i])
            new_mkt_value = mkt_value*(ret.iloc[i,:]) # Record returns over the previous period 
            # NOTE: For daily returns, each asset return should be equal to the returns matrix. But, portfolio value may be unique. 
            port = np.sum(new_mkt_value) + cash_remaining # Record new portfolio value 
            port_list.append(new_mkt_value)

            # Daily (Record daily changes in mkt value, shares, and remaining cash)
            # Remaining cash, shares - constant. Mkt value - changing. 
            # Portfolio mkt value - changing (recorded above). 
            if bool(test1['end of month'][i]) == True:
                #shares.append(s.values)
                cash_rem.append(cash_remaining)
                strat.append(x)
                mkt_val.append(new_mkt_value.values)
                mkt_value = new_mkt_value

        # When to rebalance (Rebalance at last trading day of month)

        # First entry.        
        if i == 0: 
            if bool(test1['end of month'][i]) == False:  # If we start at end of the month
                if ((test1.month.values[i] in [10,11,12]) & (test1.year.values[i]%2 == 0)) or ((test1.month.values[i] in [1,2,3]) & (test1.year.values[i]%2 == 1)): # Halloween strategy
                    X = odd_buy 
                    x = "odd aggressive"
                elif (test1.month.values[i] in [4,5,6,7,8,9]) & (test1.year.values[i]%2 == 1): 
                    X = odd_hold 
                    x = "odd passive"
                elif ((test1.month.values[i] in [10,11,12]) & (test1.year.values[i]%2 == 1)) or ((test1.month.values[i] in [1,2,3]) & (test1.year.values[i]%2 == 0)): 
                    X = even_buy 
                    x = "even aggressive"
                elif (test1.month.values[i] in [4,5,6,7,8,9]) & (test1.year.values[i]%2 == 0): 
                    X = even_hold
                    x = "even passive"
            else:                                # If we start in the middle of the month
                if ((test1.month.values[i] in [11,12]) & (test1.year.values[i]%2 == 0)) or ((test1.month.values[i] in [1,2,3,4]) & (test1.year.values[i]%2 == 1)): 
                    X = odd_buy 
                    x = "odd aggressive"
                elif (test1.month.values[i] in [5,6,7,8,9,10]) & (test1.year.values[i]%2 == 1): 
                    X = odd_hold 
                    x = "odd passive"
                elif ((test1.month.values[i] in [11,12]) & (test1.year.values[i]%2 == 1)) or ((test1.month.values[i] in [1,2,3,4]) & (test1.year.values[i]%2 == 0)): 
                    X = even_buy 
                    x = "even aggressive"
                elif (test1.month.values[i] in [5,6,7,8,9,10]) & (test1.year.values[i]%2 == 0): 
                    X = even_hold
                    x = "even passive"
                    
            strat.append(x)
            # Execute rebalance (# of shares of each asset, mkt value of each asset, cash remaining)
            mkt_value = X*port  # Market value (share X price) of each asset we will be holding 
            mkt_val.append(mkt_value)
            cash_remaining = port - np.sum(mkt_value) # Remaining cash in our portfolio 
            cash_rem.append(cash_remaining)
            
            # Tell indicator that we are invested
            invested = True

        # Rebalancing 
        else: 
            if bool(test1['end of month'][i]) == False: # Rebalance when end of month
                #print("Rebalance", test1["Date"][i])
                # Determine which strategy to use
                if ((test1.month.values[i] in [10,11,12]) & (test1.year.values[i]%2 == 0)) or ((test1.month.values[i] in [1,2,3]) & (test1.year.values[i]%2 == 1)): # Halloween strategy
                    X = odd_buy 
                    x = "odd aggressive"
                elif (test1.month.values[i] in [4,5,6,7,8,9]) & (test1.year.values[i]%2 == 1): 
                    X = odd_hold 
                    x = "odd passive"
                elif ((test1.month.values[i] in [10,11,12]) & (test1.year.values[i]%2 == 1)) or ((test1.month.values[i] in [1,2,3]) & (test1.year.values[i]%2 == 0)): 
                    X = even_buy 
                    x = "even aggressive"
                elif (test1.month.values[i] in [4,5,6,7,8,9]) & (test1.year.values[i]%2 == 0): 
                    X = even_hold
                    x = "even passive"


                ti = nasdaq_ind[(nasdaq_ind.index.month == ret.index[i].month)&(nasdaq_ind.index.year == ret.index[i].year)]
                # 2) SElL LOGIC 
                if  ((ti.Close< ti['5mo MA']).values[0]):
                    # Check for exception: 
                    # If golden cross happend in the past 6 months or year is odd, then don't sell. 
                    if (ti['gc_ind'] == 1).values | ti.index.year%2 == 1: 
                        pass
                    else:
                        #logic_sell_ind = True
                        X = logic_sell
                        x = "Logic Sell"
                elif ((ti.Close > ti['5mo MA']).values[0]):
                    print("Buy")
                    #logic_sell_ind = False
            #########################################################################

                strat.append(x)
                # Execute rebalance (# of shares of each asset, mkt value of each asset, cash remaining)
                #s = np.floor_divide((X*port),test1.iloc[i,4:]) # Determine number of shares for each asset! 
                #shares.append(s.values)
                mkt_value = X*port  # Market value (share X price) of each asset we will be holding 
                mkt_val.append(mkt_value)
                cash_remaining = port - np.sum(mkt_value) # Remaining cash in our portfolio 
                cash_rem.append(cash_remaining)

    res_mkt_val = pd.DataFrame(mkt_val)
    res_mkt_val.columns = ret.columns + ' mkt val'
    res_mkt_val.index = ret.index[-len(res_mkt_val):]
    res_mkt_val['cash_rem'] = cash_rem
    res_mkt_val['port_val'] = res_mkt_val.iloc[:, :].sum(axis=1)

    res_pct = res_mkt_val[res_mkt_val.columns[:]].div(res_mkt_val[res_mkt_val.columns[-1]], axis=0)
    res_mkt_val['strategy'] = strat
    return res_mkt_val,res_pct

In [178]:
y1 = algo2(dt_ind, ret ,nasdaq_ind)

C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:53: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False:  # If we start at end of the month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month

Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy
Buy

C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:42: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == True:
C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\2928797911.py:92: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if bool(test1['end of month'][i]) == False: # Rebalance when end of month

In [156]:
y1[0].to_excel("port_ex.xlsx")

In [180]:
# 1. 일별수익률추이
def daily_ret(result):
    report = result.copy()
    report['일별수익률'] = result['port_val'].pct_change()
    report['누적수익률'] = result['port_val'] / result['port_val'][0] - 1
    report.replace(np.nan, 0, inplace=True)
    del report['strategy']
    report1 = report
    return report1

In [181]:
daily_ret_dad = daily_ret(y1[0])

C:\Users\ewp\AppData\Local\Temp\ipykernel_24204\1661900519.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  report['누적수익률'] = result['port_val'] / result['port_val'][0] - 1

In [182]:
daily_ret_dad

Ticker,069500.KS mkt val,114260.KS mkt val,133690.KS mkt val,143850.KS mkt val,153130.KS mkt val,157450.KS mkt val,229200.KS mkt val,cash_rem,port_val,일별수익률,누적수익률
Date,,,,,,,,,,,
2015-10-01,1.400000e+09,1.000000e+09,2.100000e+09,1.400000e+09,1.000000e+09,1.000000e+09,0.000000e+00,2.100000e+09,1.000000e+10,0.000000,0.000000
2015-10-02,1.390921e+09,9.997315e+08,2.090117e+09,1.393123e+09,1.000049e+09,1.000000e+09,0.000000e+00,2.100000e+09,9.973941e+09,-0.002606,-0.002606
2015-10-05,1.392385e+09,1.000627e+09,2.115531e+09,1.412503e+09,1.000049e+09,1.000049e+09,0.000000e+00,2.100000e+09,1.002114e+10,0.004733,0.002114
2015-10-06,1.405565e+09,1.000358e+09,2.123532e+09,1.426568e+09,1.000197e+09,1.000099e+09,0.000000e+00,2.100000e+09,1.005632e+10,0.003510,0.005632
2015-10-07,1.426946e+09,9.996420e+08,2.119767e+09,1.433132e+09,1.000296e+09,1.000246e+09,0.000000e+00,2.100000e+09,1.008003e+10,0.002358,0.008003
...,...,...,...,...,...,...,...,...,...,...,...
2022-12-23,1.878181e+09,1.426351e+09,2.764182e+09,1.917757e+09,1.426479e+09,1.426347e+09,2.830963e+09,1.907349e-06,1.367026e+10,-0.018065,0.367026
2022-12-26,1.880976e+09,1.425595e+09,2.759784e+09,1.929851e+09,1.426479e+09,1.426347e+09,2.884514e+09,1.907349e-06,1.373355e+10,0.004629,0.373355
2022-12-27,1.894332e+09,1.423579e+09,2.767701e+09,1.940002e+09,1.426479e+09,1.426487e+09,2.926486e+09,1.907349e-06,1.380507e+10,0.005208,0.380507
2022-12-28,1.871969e+09,1.421940e+09,2.705023e+09,1.922077e+09,1.427231e+09,1.426976e+09,2.842542e+09,1.907349e-06,1.361776e+10,-0.013568,0.361776
2022-12-29,1.838425e+09,1.421058e+09,2.674235e+09,1.897673e+09,1.427367e+09,1.427046e+09,2.790438e+09,1.907349e-06,1.347624e+10,-0.010392,0.347624

In [183]:
%matplotlib inline
import quantstats as qs
import webbrowser
# extend pandas functionality with metrics, etc.
qs.extend_pandas()

In [188]:
qs.reports.html(daily_ret_dad['일별수익률']        # <- Input 일별수익률
                , "^GSPC", output='Halloween_kospi.html', title='Halloween_kospi')
html_file_path = r"C:\Users\ewp\OneDrive\Desktop\mySite\cra_backtest_CQRA2\Algorithm\Halloween_kospi.html"
# Open the HTML file in the default web browser
webbrowser.open(html_file_path)

[*********************100%%**********************]  1 of 1 completed
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\core\fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:1016: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Weekly"].ffill(inplace=True)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:1019: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Monthly"].ffill(inplace=True)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:1022: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Quarterly"].ffill(inplace=True)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)
c:\Users\ewp\AppData\Local\Programs\Python\Python312\Lib\site-packages\quantstats\_plotting\core.py:1025: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  port["Yearly"].ffill(inplace=True)

True